### ISSUE TITLE
rbtrace 0.4.8 doesn't install on YARV-MJIT, but does install on Ruby 2.5.0 preview 1

### ISSUE THREAD

**Issue by noahgibbs** [k0kubun/yarv-mjit#18]
I'm looking at profiling YARV-MJIT with Rails Ruby Bench. One minor issue: rbtrace version 0.4.8, which is required by Discourse and installs with Ruby 2.5.0 preview 1, fails to install on YARV-MJIT. Here's the error I see (in a sea of harmless warnings):

```
    amazon-ebs: NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void
    amazon-ebs: func(void))))
    amazon-ebs: ^~~~~~~~~
    amazon-ebs: /home/ubuntu/rails_ruby_bench/work/prefix/yarv-mjit/include/ruby-2.5.0/ruby/backward.h:39:58:
    amazon-ebs: note: in expansion of macro ‘DEPRECATED’
    amazon-ebs: NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void
    amazon-ebs: func(void))))
    amazon-ebs: ^~~~~~~~~~
    amazon-ebs: /home/ubuntu/rails_ruby_bench/work/prefix/yarv-mjit/include/ruby-2.5.0/ruby/backward.h:53:1:
    amazon-ebs: note: in expansion of macro ‘DECLARE_DEPRECATED_INTERNAL_FEATURE’
    amazon-ebs: DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_frame_method_id_and_class);
    amazon-ebs: ^
    amazon-ebs: rbtrace.c:329:5: error: too many arguments to function
    amazon-ebs: ‘rb_frame_method_id_and_class’
    amazon-ebs: rb_frame_method_id_and_class(&_mid, &_klass);
    amazon-ebs: ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by k0kubun** [comment]
It should fail on Ruby trunk too https://github.com/ruby/ruby/commit/c7c173a6185f8fe3c9cf5116a2362af95247a5f7.

Probably ko1 missed rbtrace's usage. We should fix this in rbtrace or ruby trunk somehow.

**Comment by k0kubun** [comment]
I fixed in Ruby trunk https://github.com/ruby/ruby/commit/857827e3eed915543ac9d4d2541179ea4ded8eee and rebased YARV-MJIT from the upstream. So this issue is fixed for now.

There should be some other things we should fix to let YARV-MJIT work with Rails. I'm working on it now.

**Comment by noahgibbs** [comment]
Excellent. I had modified my copy of Discourse to not install rbtrace, but I'll try again with it. Thank you!
