### ISSUE TITLE
test/drb/test_drb.rb may cause SEGV with "-j:aot=1"

### ISSUE THREAD

**Issue by wanabe** [k0kubun/yarv-mjit#33]
The following command may cause SEGV.
```
$ make test-all RUN_OPTS="--disable-gems -j:aot=1" TESTS=../../test/drb/test_drb.rb
Run options: "--ruby=./miniruby -I../../lib -I. -I.ext/common  ../../tool/runruby.rb --extout=.ext  -- --disable-gems -j:aot=1" --excludes-dir=../../test/excludes --name=!/memory_leak/

# Running tests:

[57/57] DRbTests::TestDRbYield#test_06_taint/home/wanabe/ruby/ruby/lib/drb/drb.rb:925: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.0dev (2017-12-29 yarv-mjit/jump.. 61511) [x86_64-linux]

(snip)
```

I have met similar results with "-j" option before, but it is not 100%.

**Comment by wanabe** [comment]
> TESTS=../../test/drb/test_drb.rb

I'm sorry, this path is an environment dependent.
Please replace suitable path on reading.

**Comment by wanabe** [comment]
I reduced reproducible code.

```
$ ./miniruby -j:aot=1 -e 'def foo; [].push(bar); end; def bar; raise rescue nil; end; foo; foo'
Traceback (most recent call last):
	1: from -e:1:in `<main>'
-e:1:in `foo': undefined method `push' for 143163393:Integer (NoMethodError)
```

**Comment by wanabe** [comment]
This issue will be fixed after resolving https://github.com/k0kubun/yarv-mjit/pull/30#issuecomment-354215062 : 
> * On raising exception, machine stack (VALUE stack[n]) should be copied to YARV stack
>   * ensure, rescue may see local variable in main ISeq

And https://bugs.ruby-lang.org/issues/12589#note-38 : 
> We found potential bugs in exception handling and TracePoint support, but it's considered to be not so hard to fix in our discussion.

**Comment by k0kubun** [comment]
While I considered some ideas, I fixed this by https://github.com/k0kubun/yarv-mjit/commit/e8a7bd8a9b28ee07a764dca975ed183633e23b02 and fortunately performance is not changed at least with optcarrot.

Probably similar to your idea: https://twitter.com/wannabe53/status/947410769183834112

**Comment by k0kubun** [comment]
Umm... but it starts to die with rubygems prelude...

**Comment by k0kubun** [comment]
As it causes another issue, I reverted the commit for now. Reopening.

**Comment by asuhan** [comment]
Possibly related: if I build in debug mode, it crashes reliably (most often around DRb or Fiddle tests) with the following trace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f38f5bfaf5d in __GI_abort () at abort.c:90
#2  0x0000559480df63ea in die () at error.c:558
#3  0x0000559480df6631 in rb_bug_context (ctx=0x7f38f58e4540, fmt=0x559480e3105f "Segmentation fault at %p") at error.c:588
#4  0x0000559480cf1846 in sigsegv (sig=11, info=0x7f38f58e4670, ctx=0x7f38f58e4540) at signal.c:928
#5  <signal handler called>
#6  0x0000559480c4ac36 in inlinable_cfunc_p (cc=0x5594882d3808) at mjit_compile.c:76
#7  0x0000559480c4b017 in compile_send (f=0x7f38f0000b90, insn=47, operands=0x5594878d5630, stack_size=4, with_block=1) at mjit_compile.c:157
#8  0x0000559480c4c706 in compile_insn (f=0x7f38f0000b90, body=0x5594874fe410, insn=47, operands=0x5594878d5630, pos=13, status=0x7f38f58e4d60, b=0x7f38f58e4d18) at mjit_compile.c:497
#9  0x0000559480c4e029 in compile_insns (f=0x7f38f0000b90, body=0x5594874fe410, stack_size=0, pos=13, status=0x7f38f58e4d60) at mjit_compile.c:800
#10 0x0000559480c4e321 in mjit_compile (f=0x7f38f0000b90, body=0x5594874fe410, funcname=0x7f38f58e4dd0 "_mjit912") at mjit_compile.c:854
#11 0x0000559480c49407 in convert_unit_to_func (unit=0x55948710bff0) at mjit.c:709
#12 0x0000559480c497fa in worker () at mjit.c:788
#13 0x0000559480d27285 in mjit_worker (arg=0x559480c496e8 <worker>) at thread_pthread.c:1806
#14 0x00007f38f69bb7fc in start_thread (arg=0x7f38f58e5700) at pthread_create.c:465
#15 0x00007f38f5cd6b0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
More precisely, `cc->me->def` in `inlinable_cfunc_p` has a small integer value (cannot be a valid pointer). Could it possibly be that the inline cache is somehow invalidated by the time the unit gets to be compiled by the worker? In any case, the behavior looks a lot like a race, it's very sensitive to timing: if I run the tests with verbose output or compile in release mode / play with the JIT debug flags, it crashes a lot less (in release mode, all tests pass for example).

Just in case it matters, my environment is Ubuntu 17.10 on x64 and gcc 7.2.

**Comment by k0kubun** [comment]
> More precisely, cc->me->def in inlinable_cfunc_p has a small integer value (cannot be a valid pointer). Could it possibly be that the inline cache is somehow invalidated by the time the unit gets to be compiled by the worker? In any case, the behavior looks a lot like a race, it's very sensitive to timing: if I run the tests with verbose output or compile in release mode / play with the JIT debug flags, it crashes a lot less (in release mode, all tests pass for example).

Thanks to report. Even the failed test is the same, this one should be another issue. So I separated the issue: https://github.com/k0kubun/yarv-mjit/issues/35

**Comment by k0kubun** [comment]
To make initial merge safe, I'll retry to take VM stack approach again https://github.com/k0kubun/yarv-mjit/commit/87090467aaf4e40de1d862cbb65d6f852ef9bfca. With the commit, drb test always succeeds.
